[globals]
; (Optional) Global variables can go here

[context-local]
exten => _042X.,1,Goto(ext-routing,+${EXTEN},1)
exten => _+042X.,1,Goto(ext-routing,${EXTEN},1)
exten => _X!,1,Goto(ext-local,${EXTEN},1)

[context-enum]
exten => _00X!,1,Goto(ext-routing,+${EXTEN:2},1)
exten => _+X!,1,Goto(ext-routing,${EXTEN},1)
exten => _X!,1,Goto(ext-routing,+${EXTEN},1)

[messages-local]
exten => _042X.,1,Goto(msg-routing,+${EXTEN},1)
exten => _+042X.,1,Goto(msg-routing,${EXTEN},1)
exten => _X!,1,Goto(msg-local,${EXTEN},1)

[messages-enum]
exten => _00X!,1,Goto(msg-routing,+${EXTEN:2},1)
exten => _+X!,1,Goto(msg-routing,${EXTEN},1)
exten => _X!,1,Goto(msg-routing,+${EXTEN},1)

[ext-local]
exten => _XXXX,1,NoOp(Call ${EXTEN})
 same => n,NoOp(IP : ${CHANNEL(pjsip,remote_addr)})
 same => n,Log(NOTICE, Incoming call from ${CALLERID(num)} to ${EXTEN})
 same => n,Dial(PJSIP/${EXTEN},30)
 same => n,Hangup()
exten => 600,1,NoOp(Call ${EXTEN})
 same => n,NoOp(IP : ${CHANNEL(pjsip,remote_addr)})
 same => n,Log(NOTICE, Incoming call from ${CALLERID(num)} to ${EXTEN})
 same => n,Answer()
 same => n,Echo()
 same => n,Hangup()
exten => 700,1,NoOp(Call ${EXTEN})
 same => n,NoOp(IP : ${CHANNEL(pjsip,remote_addr)})
 same => n,Log(NOTICE, Incoming call from ${CALLERID(num)} to ${EXTEN})
 same => n,Answer()
 same => n(music),Playback(hello-world)
 same => n,Goto(music)
 same => n,Hangup()
exten => 800,1,NoOp(Call ${EXTEN})
 same => n,NoOp(IP : ${CHANNEL(pjsip,remote_addr)})
 same => n,Answer()
 same => n,Playback(silence/1&your&number&is)
 same => n,SayAlpha(${CALLERID(num)})
 same => n,Hangup()

[ext-routing]
exten => _+04240000.,1,Goto(ext-local,${EXTEN:9},1)
exten => _+042X.,1,NoOp(DN42 ENUM Lookup: ${EXTEN})
 same => n,NoOp(IP : ${CHANNEL(pjsip,remote_addr)})
 same => n,Set(NUM=${EXTEN:1})
 same => n,Set(URI=${ENUMLOOKUP(${NUM},sip,,,tel.dn42)})
 same => n,GotoIf($["${URI}"=""]?failed)
 same => n,Set(URI=sip:${URI})
 same => n,NoOp(Dial URI=${URI})
 same => n,Dial(PJSIP/peer-enum-outbound/${URI},60)
 same => n,Hangup()
 same => n(failed),Playback(ss-noservice)
 same => n,Hangup()

[msg-local]
exten => _X.,1,NoOp(Incoming MESSAGE)
 same => n,NoOp(IP : ${MESSAGE_DATA(PJSIP_RECVADDR)})
 same => n,NoOp(From : ${MESSAGE(from)})
 same => n,Set(USER=${CUT(CUT(MESSAGE(from),@,1),:,2)})
 same => n,Set(MESSAGE(from)=<sip:${USER}@sip.example.dn42>)
 same => n,NoOp(To   : ${MESSAGE(to)})
 same => n,Set(USER=${CUT(CUT(MESSAGE(to),@,1),:,2)})
 same => n,Set(MESSAGE(to)=pjsip:${USER}@sip.example.dn42)
 same => n,NoOp(Body : ${MESSAGE(body)})
 same => n,MessageSend(pjsip:${EXTEN})
 same => n,NoOp(Status=${MESSAGE_SEND_STATUS})
 same => n,Hangup()

[msg-routing]
exten => _+04240000.,1,Goto(msg-local,${EXTEN:9},1)
exten => _+042X.,1,NoOp(DN42 ENUM Lookup: ${EXTEN})
 same => n,NoOp(IP : ${MESSAGE_DATA(PJSIP_RECVADDR)})
 same => n,NoOp(From : ${MESSAGE(from)})
 same => n,Set(USER=${CUT(CUT(MESSAGE(from),@,1),:,2)})
 same => n,Set(SUSER=${USER})
 same => n,Set(MESSAGE(from)=<sip:+04240000${USER}@sip.example.dn42>)
 same => n,NoOp(To   : ${MESSAGE(to)})
 same => n,Set(USER=${CUT(CUT(MESSAGE(to),@,1),:,2)})
 same => n,Set(MESSAGE(to)=pjsip:${USER}@sip.example.dn42)
 same => n,NoOp(Body : ${MESSAGE(body)})
 same => n,Set(NUM=${EXTEN:1})
 same => n,Set(URI=${ENUMLOOKUP(${NUM},sip,,,tel.dn42)})
 same => n,Set(URI=sip:${URI})
 same => n,MessageSend(pjsip:peer-enum-outbound/${URI})
 same => n,NoOp(Status=${MESSAGE_SEND_STATUS})
 same => n,GotoIf($["${MESSAGE_SEND_STATUS}"="SUCCESS"]?done:bounce)
 same => n(bounce),Set(MESSAGE(from)=<sip:${USER}@sip.example.dn42>)
 same => n,Set(MESSAGE(body)=消息发送失败，用户可能离线或不存在。)
 same => n,MessageSend(pjsip:${SUSER})
 same => n(done),Hangup()
