[global]
type=global
endpoint_identifier_order=auth_username,username,ip

[transport-udp4]
type=transport
protocol=udp
bind=x.x.x.x:5060
local_net=172.16.0.0/12
local_net=10.0.0.0/8
local_net=192.168.0.0/16

[transport-udp6]
type=transport
protocol=udp
bind=[xxxx]:5060
local_net=fc00::/7

[phone-template-endpoint](!)
type=endpoint
context=context-local
message_context=messages-local
allow=!all,opus,g722,alaw,ulaw

rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
direct_media=no

rtp_timeout=60
tone_zone=cn
trust_id_inbound=yes

send_pai=yes

[phone-template-auth](!)
type=auth
auth_type=userpass

[phone-template-aor](!)
type=aor
max_contacts=1
remove_existing=yes
qualify_frequency=15

[0001](phone-template-aor)
[0001](phone-template-auth)
username=0001
password=0001

[0001](phone-template-endpoint)
auth = 0001
aors = 0001
callerid="Example 1" <+042400000001>

[0002](phone-template-aor)
[0002](phone-template-auth)
username=0002
password=0002

[0002](phone-template-endpoint)
auth = 0002
aors = 0002
callerid="Example 2" <+042400000002>

; -- 入站 --
[peer-enum-inbound]
type=endpoint
context=context-enum
message_context=messages-enum
allow=!all,opus,g722,alaw,ulaw
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
direct_media=no

[peer-enum-inbound-id]
type=identify
endpoint=peer-enum-inbound
match=10.0.0.0/8
match=172.16.0.0/12
match=192.168.0.0/16
match=fc00::/7

; -- 出站 --
[peer-enum-outbound]
type=endpoint
allow=!all,opus,g722,alaw,ulaw
send_pai=yes
